[tool.pyright]
pythonVersion = "3.10"

typeCheckingMode = "strict"
reportMissingTypeStubs = false

reportUnusedVariable = "warning"
reportUnusedImport = "warning"
reportUnusedFunction = "warning"

reportIncompatibleMethodOverride = false

reportUnknownMemberType = false

[tool.black]

[tool.isort]
profile = "black"
